# Testing and Comparing Different Methods

First let's import the necessary libraries and implementations for the methods.

In [6]:
import numpy as np
import source_code as sc
from source_code import eigenvalues_characteristic_polynomial_method, eigenvalue_power_method, eigenvalues_QR_algorithm

We will now proceed to test all the matrices using each of the methods and compare the results. Specifically, we will evaluate the number of iterations required by each method and compare the eigenvalues they produce against the results obtained from NumPy.

In [19]:
def compare(matrix, initial_guess,tol=1e-6):
    """
    Compares eigenvalues and eigenvectors from different methods with NumPy's results and calculates the error.

    Args:
        matrix (list[list[float]] or np.ndarray): The matrix for which eigenvalues and eigenvectors are computed.
        tol (float): Tolerance for comparison.

    Returns:
        dict: A dictionary containing the eigenvalues and eigenvectors from each method,
              NumPy's results, and the errors for each method.
    """
    results = {}
    
    # Convert the matrix to a numpy array if it's not already
    matrix = np.array(matrix, dtype=float)
    np_eigenvalues_M = np.linalg.eigvals(M)
    real_eigenvalues_M = sorted(np_eigenvalues_M[np.isreal(np_eigenvalues_M)].real)
    np_eigenvalues, np_eigenvectors = np.linalg.eig(matrix)
    real_np_eigenvalues = sorted(np_eigenvalues[np.isreal(np_eigenvalues)].real)
    np_eigenvectors = np.array([np_eigenvectors[:, i] for i in range(len(np_eigenvalues))])
    results["numpy"] = {"eigenvalues": real_np_eigenvalues, "eigenvectors": np_eigenvectors}

    # Characteristic Polynomial Method
    eigenvalues_poly = eigenvalues_characteristic_polynomial_method(matrix, show=False)
    poly_error = [abs(a - b) for a, b in zip(eigenvalues_poly, real_np_eigenvalues)]
    results["characteristic_polynomial"] = {
        "eigenvalues": eigenvalues_poly,
        "errors": poly_error,
        "within_tolerance": all(e <= tol for e in poly_error)
    }

    # QR Algorithm
    eigenvalues_M, qr_iterations = eigenvalues_QR_algorithm(matrix)
    qr_error = []
    for my_eigenvalue, np_eigenvalue in zip(eigenvalues_M, real_eigenvalues_M):
        qr_error.append(abs(my_eigenvalue - np_eigenvalue))
    
    results["qr_algorithm"] = {
        "eigenvalues": eigenvalues_M,
        "errors": qr_error,
        "within_tolerance": all(e <= tol for e in qr_error),
        "iterations": qr_iterations
    }

    # Power Method 
    dominant_eigenvalue, dominant_eigenvector, power_iterations = eigenvalue_power_method(matrix, initial_guess)
    dominant_error = abs(dominant_eigenvalue - max(real_np_eigenvalues))
    numpy_dominant_eigenvector = np_eigenvectors[np.argmax(real_np_eigenvalues)]
    results["power_method"] = {
        "dominant_eigenvalue": dominant_eigenvalue,
        "eigenvector": dominant_eigenvector,
        "error": dominant_error,
        "within_tolerance": dominant_error <= tol,
        "iterations": power_iterations
    }

    # Results
    print("Eigenvalue and Eigenvector Comparison\n")
    print("NumPy Results:")
    print(f"Eigenvalues: {real_np_eigenvalues}")
    print("Eigenvectors:")
    for vec in np_eigenvectors:
        print(vec)
    print("\n")

    print("Characteristic Polynomial Method:")
    print(f"  Eigenvalues: {eigenvalues_poly}")
    print(f"  Errors: {poly_error}")
    print(f"  Within Tolerance: {results['characteristic_polynomial']['within_tolerance']}\n")

    print("Power Method:")
    print(f"  Dominant Eigenvalue: {dominant_eigenvalue}")
    print(f"  Error: {dominant_error}")
    print(f"  Eigenvector: {dominant_eigenvector}")
    print(f"  Iterations: {power_iterations}")
    print(f"  Within Tolerance: {results['power_method']['within_tolerance']}\n")
    
    print("QR Algorithm:")
    print(f"  Eigenvalues: {eigenvalues_M}")
    print(f"  Errors: {qr_error}")
    print(f"  Iterations: {qr_iterations}")
    print(f"  Within Tolerance: {results['qr_algorithm']['within_tolerance']}\n")
    
    return results

## Test for Matrix A

$ A = \begin{bmatrix} 2 & 1 \\ 3 & 4 \end{bmatrix} $


In [25]:
tol = 1e-6
A = np.array([[2, 1], [3, 4]])
x = np.random.rand(A.shape[0])
results_A = compare_with_numpy(A, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [1.0, 5.0]
Eigenvectors:
[-0.70710678  0.70710678]
[-0.31622777 -0.9486833 ]


Characteristic Polynomial Method:
  Eigenvalues: [1.0, 5.0]
  Errors: [0.0, 0.0]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 5.000000000101592
  Error: 1.0159162400213972e-10
  Eigenvector: [0.31622777 0.9486833 ]
  Iterations: 13
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [0.9999999999999997, 4.999999999999999]
  Errors: [2.087934923662562, 5.46744323473112]
  Iterations: 464
  Within Tolerance: False



## Test for Matrix B

$ B = \begin{bmatrix} 3 & 2 \\ 3 & 4 \end{bmatrix} $

In [26]:
tol = 1e-6
B = np.array([[3, 2], [3, 4]])
x = np.random.rand(B.shape[0])
results_B = compare_with_numpy(B, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [1.0, 6.0]
Eigenvectors:
[-0.70710678  0.70710678]
[-0.5547002  -0.83205029]


Characteristic Polynomial Method:
  Eigenvalues: [1.0, 6.0]
  Errors: [0.0, 0.0]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 6.000000000151369
  Error: 1.5136869535581354e-10
  Eigenvector: [0.5547002  0.83205029]
  Iterations: 11
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [1.0, 6.0]
  Errors: [2.0879349236625626, 6.467443234731121]
  Iterations: 417
  Within Tolerance: False



## Test for Matrix C

$ C = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix} $

In [27]:
tol = 1e-6
C = np.array([[2, 3], [1, 4]])
x = np.random.rand(C.shape[0])
results_C = compare_with_numpy(C, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [1.0, 5.0]
Eigenvectors:
[-0.9486833   0.31622777]
[-0.70710678 -0.70710678]


Characteristic Polynomial Method:
  Eigenvalues: [1.0, 5.0]
  Errors: [0.0, 0.0]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 5.000000000191516
  Error: 1.915161362830986e-10
  Eigenvector: [0.70710678 0.70710678]
  Iterations: 13
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [1.0, 4.999999999999998]
  Errors: [2.0879349236625626, 5.467443234731119]
  Iterations: 464
  Within Tolerance: False



## Test for Matrix D

$ D = \begin{bmatrix} 1 & 1 & 2 \\ 2 & 1 & 1 \\ 1 & 1 & 3 \end{bmatrix} $


In [28]:
tol = 1e-6
D = np.array([[1, 1, 2], [2, 1, 1], [1, 1, 3]])
x = np.random.rand(D.shape[0])
results_D = compare_with_numpy(D, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [-0.28514248182978585, 0.7781238377368096, 4.507018644092976]
Eigenvectors:
[-0.53231709 -0.49863934 -0.6841033 ]
[-0.49762292  0.86033768 -0.11041066]
[-0.1297142  -0.88103974  0.45491011]


Characteristic Polynomial Method:
  Eigenvalues: [-0.2851424818297853, 0.7781238377368085, 4.507018644092975]
  Errors: [5.551115123125783e-16, 1.1102230246251565e-15, 8.881784197001252e-16]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 4.507018644167408
  Error: 7.44320161061296e-11
  Eigenvector: [0.53231709 0.49863934 0.6841033 ]
  Iterations: 11
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [-0.28514248182978563, 0.7781238377368092, 4.507018644092973]
  Errors: [0.802792441832777, 1.2455670724679302, 2.7789027358033316]
  Iterations: 999
  Within Tolerance: False



## Test for Matrix E

$ E = \begin{bmatrix} 1 & 1 & 2 \\ 2 & 1 & 3 \\ 1 & 1 & 1 \end{bmatrix} $


In [29]:
tol = 1e-6
E = np.array([[1, 1, 2], [2, 1, 3], [1, 1, 1]])
x = np.random.rand(E.shape[0])
results_E = compare_with_numpy(E, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [-0.6920214716300966, -0.3568958678922092, 4.0489173395223075]
Eigenvectors:
[-0.51769363 -0.74808896 -0.41515805]
[-0.85467668  0.21108771  0.47430977]
[-0.26822309 -0.75154439  0.6026918 ]


Characteristic Polynomial Method:
  Eigenvalues: [-0.6920214716300959, -0.3568958678922095, 4.048917339522307]
  Errors: [7.771561172376096e-16, 3.3306690738754696e-16, 8.881784197001252e-16]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 4.0489173398372085
  Error: 3.149009941694203e-10
  Eigenvector: [0.51769363 0.74808896 0.41515805]
  Iterations: 11
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [-0.6920214716300964, -0.35689586789220923, 4.048917339522307]
  Errors: [0.3959134520324662, 0.11054736683891181, 2.320801431232665]
  Iterations: 999
  Within Tolerance: False



## Test for Matrix F

$ F = \begin{bmatrix} 2 & 1 & 2 \\ 1 & 1 & 3 \\ 1 & 1 & 1 \end{bmatrix} $


In [30]:
tol = 1e-6
F = np.array([[2, 1, 2], [1, 1, 3], [1, 1, 1]])
x = np.random.rand(F.shape[0])
results_F = compare_with_numpy(F, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [-0.7615571818318907, 0.6366717620673152, 4.1248854197645715]
Eigenvectors:
[-0.67550236 -0.61159354 -0.41188579]
[-0.72653358  0.66793428  0.16128473]
[-0.07072589 -0.84969749  0.52250553]


Characteristic Polynomial Method:
  Eigenvalues: [-0.7615571818318908, 0.6366717620673163, 4.124885419764568]
  Errors: [1.1102230246251565e-16, 1.1102230246251565e-15, 3.552713678800501e-15]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 4.124885420010473
  Error: 2.4590196545659637e-10
  Eigenvector: [0.67550236 0.61159354 0.41188579]
  Iterations: 12
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [-0.761557181831891, 0.6366717620673172, 4.124885419764577]
  Errors: [0.3263777418306716, 1.1041149967984383, 2.396769511474935]
  Iterations: 999
  Within Tolerance: False



## Test for Matrix G

$ G = \begin{bmatrix} 1 & 1 & 1 & 2 \\ 2 & 1 & 1 & 1 \\ 3 & 2 & 1 & 2 \\ 2 & 1 & 1 & 4 \end{bmatrix} $


In [31]:
tol = 1e-6
G = np.array([[1, 1, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2], [2, 1, 1, 4]])
x = np.random.rand(G.shape[0])
results_G = compare_with_numpy(G, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [-0.7356415384387976, -0.4074562701381244, 1.5085633449433251, 6.634534463633592]
Eigenvectors:
[0.38941594 0.35142164 0.55977506 0.6414904 ]
[-0.10866639 -0.54839569 -0.61625428  0.55469311]
[ 0.65148076 -0.31969406 -0.68513144 -0.06295578]
[ 0.38913343 -0.80095815  0.44482357 -0.09577685]


Characteristic Polynomial Method:
  Eigenvalues: [-0.7356415384387962, -0.40745627013812413, 1.5085633449433264, 6.634534463633594]
  Errors: [1.4432899320127035e-15, 2.7755575615628914e-16, 1.3322676295501878e-15, 1.7763568394002505e-15]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 6.634534463552596
  Error: 8.099654280613322e-11
  Eigenvector: [0.38941594 0.35142164 0.55977506 0.6414904 ]
  Iterations: 14
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [-0.735641538438797, -0.407456270138124, 1.5085633449433236, 6.634534463633598]
  Errors: [0.35229338522376563, 0.059986964592997016, 0.219552563346318, 0.

## Test for Matrix H

$ H = \begin{bmatrix} 1 & 2 & 1 & 2 \\ 2 & 1 & 1 & 1 \\ 3 & 2 & 1 & 2 \\ 2 & 1 & 1 & 4 \end{bmatrix} $

In [32]:
tol = 1e-6
H = np.array([[1, 2, 1, 2], [2, 1, 1, 1], [3, 2, 1, 2], [2, 1, 1, 4]])
x = np.random.rand(H.shape[0])
results_H = compare_with_numpy(H, tol)

Eigenvalue and Eigenvector Comparison

NumPy Results:
Eigenvalues: [-1.0879349236625626, -0.46744323473112104, 1.7281159082896416, 6.82726225010404]
Eigenvectors:
[-0.42853133 -0.34899468 -0.55406667 -0.62255421]
[-0.24289613 -0.4838935  -0.52400705  0.65746876]
[-0.71363438  0.35215497  0.598272    0.09372011]
[-0.28400892 -0.22663858  0.93115005 -0.03055296]


Characteristic Polynomial Method:
  Eigenvalues: [-1.087934923662562, -0.46744323473112087, 1.7281159082896396, 6.827262250104043]
  Errors: [6.661338147750939e-16, 1.6653345369377348e-16, 1.9984014443252818e-15, 3.552713678800501e-15]
  Within Tolerance: True

Power Method:
  Dominant Eigenvalue: 6.827262250009321
  Error: 9.471889939050016e-11
  Eigenvector: [0.42853133 0.34899468 0.55406667 0.62255421]
  Iterations: 15
  Within Tolerance: True

QR Algorithm:
  Eigenvalues: [-1.0879349236625615, -0.46744323473112104, 1.7281159082896402, 6.827262250104039]
  Errors: [1.1102230246251565e-15, 0.0, 1.3322676295501878e-15, 8.88178

In [8]:
tol = 1e-6
for i, M in enumerate(matrices):
    eigenvalues_M, oo = eigenvalues_QR_algorithm(M)
    np_eigenvalues_M = np.linalg.eigvals(M)

    # Filtrar los eigenvalues en R
    real_eigenvalues_M = sorted(np_eigenvalues_M[np.isreal(np_eigenvalues_M)].real)

    print(eigenvalues_M)

    # testear los eigenvalues que produce el metodo con los que produce numpy
    qr_error = []
    for my_eigenvalue, np_eigenvalue in zip(eigenvalues_M, real_eigenvalues_M):
        qr_error.append(abs(my_eigenvalue - np_eigenvalue)) 

    # testear los eigenvectors viendo que cumplen la regla Mv = lambdav
    for lambd in eigenvalues_M:
        v = sc.eigenvector(M, lambd, show=False) # Si selecciona show = True muestra mas informacion
        assert np.linalg.norm(v) > 0, "El vector propio es cero"

        Mv = np.dot(M, v)
        lambd_v = lambd * v
        assert np.linalg.norm(Mv - lambd_v) <= tol, f"Error muy alto para la matriz en el indice {i}"

print("No se presento ningun error para la matriz, los eigenvalues coinciden con los generados por numpy y los vectores asociados cumplen la regla de multiplicacion")

[0.9999999999999997, 4.999999999999999]
[1.0, 6.0]
[1.0, 4.999999999999998]
[-0.28514248182978563, 0.7781238377368092, 4.507018644092973]
[-0.6920214716300964, -0.35689586789220923, 4.048917339522307]
[-0.761557181831891, 0.6366717620673172, 4.124885419764577]
[-0.735641538438797, -0.407456270138124, 1.5085633449433236, 6.634534463633598]
[-1.0879349236625615, -0.46744323473112104, 1.7281159082896402, 6.827262250104039]
No se presento ningun error para la matriz, los eigenvalues coinciden con los generados por numpy y los vectores asociados cumplen la regla de multiplicacion
